language: python
python:
  - "3.6"

install:
  - pip install -r requirements.txt

script:
  - flake8
  - coverage run -m pytest tests/
  - coverage report .

deploy:
  provider: elasticbeanstalk
  access_key_id: $AWSEBS_ID
  secret_access_key:
    secure: $AWSEBS_KEY
  region: "us-east-1"
  app: "waninger"
  env: "Waninger-env"
  bucket_name: "elasticbeanstalk-us-east-1-701856502070"

after_success:
  - coveralls