language: python
python:
  - "3.6"

install:
  - pip install -r requirements.txt

script:
  - pytest

deploy:
  provider: elasticbeanstalk
  access_key_id: "chzjSlHhuwBdw+QnzSdyd5jWdEtY3MXBMR2MPFOoY3XBNbacUB7nn3j8rRUxNfUuqUijppMh0LOyAhmtZCol4JQEi6jRw/Oivltts7wBj2eNeb0RdbRrltM18yI9YUCG8ai6LMw4WM0f9pKVoMvJp+fC+wN1vAmxlu1SrBEu6WNBk5GifVwwKJxA7U1zqcIQ8zb6QHbFRRL3xohI3V1HlsyLtgwwuApaVkO4em9ivSX3mkeMU6tLNiWUCSyP9e/5XcoYVcMq0EWSzgDPaLMKdIrabi/CX1ftZXqFUUVk47m6GnldG4wCMOIUXen9NQudaROFC/tahFR3L9YU0a+MeeUMQEaAG911vaFiI6EZA9UaLQb8oV7ktIw6zBIuwwhnKgLvAq/HeY12/mkQ59g842T7mj+SmeXcvmaH+P+UVyhrfgww0pYna3brK3UjE3Xj9y40FyT6yF8gwjd+lDdKe45b0m5Q9Ye7SgiMw+IiLoMYhuQPEgMhRoCLySRjK+kUt8bqLuD+D91OY2HexwGwLLT/uTLdb9m75PYMabKemc0c9xZCwP7wy+itjUht1a3Pvxg2uVg4EJjd+LTsEpKotng/9Xt+vJZHcrzIW0yINz1wC/0OPHv7Wwfc5yWA4Z1JSAw+11GKHsQb0jVHx4Ipi5AxQlVriVIAuR99yIFp/WE="
  secret_access_key:
    secure: "IwHpIXapM7HtCgHpenPyRmSrOSHqSm/jDu/JG7qzWx70bFQA86XcSuaq+v2DhTbnfYFaw1ZnwMXDvUVT1RFo+1UlR/ihnvMY0jz/L34SAyYof34m2gSQpoYWB+UykkoQW7UaasCQ4WF5cIq7cl7iWSxSU9J+WNp/ybqy/w47WDLjxMBA7wpGdNzGHJ+jjz3ykftl+7w0QnqSOF00UWRjLEuRp0Bzi9uaSS8iKrYhlSJ0F8tJqRpKuRMo6pglWttiqsFZuD7HjG/Z9qjeUMkkxdpHtGSZk/99GabPlq1dRR3Nua1USimac2kvOSCz5LS3XrapLSZvPyW+Ao2ZMPJwgfDmC+tz+PXJnAqVoHAQdbI1TO0C6ZQQHqabgCv18Xpky8EhwD+XrYVz1Cw7XWDlwybYx82JJG77gW8vKlImph8w79KMQlOX1eUq4zmIGedtEEOGP3h4m2Up7J8A0/qNcYhZtKgAopFcwDoc7Q+D3+STl83CldTu/EuvnmkLMoGtENgDPUeet0vPjpz34q3RlWdTqhGCoDiuso8lpA3JUrdjspW3LmYVrZEykFFRbirl2UxvD+HUdgoByuxuaHiQ5a2oe/tl+jJjcX3B3ZYyOo37KpoznDC2vnmZ+tciFPJV3g47Vc67njk30xNrMRPxo9y7iX1AOJyMJzvAuGps24E="
  region: "us-east-1"
  app: "waninger"
  env: "Waninger-env"
  bucket_name: "elasticbeanstalk-us-east-1-701856502070"
  edge: true