language: python

python:
  - "3.6"

install:
  - pip install coverage
  - pip install coveralls
  - pip install -r requirements.txt

script:
  - coverage run -m pytest waninger/tests/

deploy:
  provider: elasticbeanstalk
  access_key_id: $AWSEBS_ID
  secret_access_key:
    secure: $AWSEBS_KEY
  region: "us-east-1"
  app: "waninger"
  env: "Waninger-env-1"
  bucket_name: "elasticbeanstalk-us-east-1-701856502070"

after_success:
  - coverage report
  - coveralls
